name: SSH into Instance

on:
  push:
    branches:
      - master

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ssh client
      run: sudo apt-get install -y sshpass

    - name: SSH into instance
      run: |
        sshpass -p 'Qmobilea34@' ssh -o StrictHostKeyChecking=no -p 222 ubuntu@44.195.207.159
        # Replace '44.195.207.159' with the IP address of your instance
